env:
  browser: true
  es6: false
extends: 'eslint:recommended'
ecmaFeatures:
  blockBindings: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - VariableDeclarator: {"var": 2, "let": 2, "const": 3}
  linebreak-style:
    - error
    - unix
  no-var: off
  no-console: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always
