<div class="spacer spacer-xs"></div>
<div class="row">
  <div class="col-sm-10">
    <div class="spacer spacer-xs"></div>
    {% include '../atoms/skills.swig' %}
    <div class="spacer spacer-xs"></div>
    <div class="spacer spacer-xs"></div>
    <div id="pie-chart" class="pie-chart"></div>
    <div class="spacer spacer-sm"></div>
    <hr>
  </div>
  <div class="col-sm-2 tools tools-vertical">
    <a href="https://angularjs.org/"><i class="icon icon-angular-simple"></i></a>
    <a href="http://getbootstrap.com/" target="_blank"><i class="icon icon-bootstrap"></i></a>
    <a href="http://yeoman.io/" target="_blank"><i class="icon icon-yeoman"></i></a>
    <a href="http://gulpjs.com/" target="_blank"><i class="icon icon-gulp"></i></a>
    <a href="https://www.mongodb.org/" target="_blank"><i class="icon icon-mongodb"></i></a>
    <a href="https://nodejs.org/" target="_blank"><i class="icon icon-nodejs-small"></i></a>
    <a href="https://git-scm.com/" target="_blank"><i class="icon icon-git"></i></a>
    <a href="https://wordpress.org/" target="_blank"><i class="icon icon-wordpress"></i></a>
    <a href="https://jquery.com/" target="_blank"><i class="icon icon-jquery-logo"></i></a>
    <a href="http://ionicframework.com/" target="_blank"><i class="icon icon-ionic"></i></a>
    <a href="https://www.npmjs.com/" target="_blank"><i class="icon icon-npm"></i></a>
  </div>
</div>
<div class="spacer spacer-xs"></div>
<div id="contributions" class="contributions"></div>
